'use strict';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const st={csrf:'',nodes:[],current:null,currentProc:null,history:[],range:1,processes:[],update:null,settings:null,confirm:null,refreshTimer:null};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function show(id){$('#'+id)?.classList.add('show')} function hide(id){$('#'+id)?.classList.remove('show')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)}
function fmtPct(v){return Number.isFinite(+v)?Math.round(+v)+'%':'--'}
function fmtBytes(v){v=+v||0;const u=['B','KB','MB','GB','TB'];let i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return (i===0||v>=100?v.toFixed(0):v>=10?v.toFixed(1):v.toFixed(2))+' '+u[i]}
function fmtRate(v){return fmtBytes(v)+'/s'}
function fmtUptime(s){s=Math.max(0,Math.floor(+s||0));const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?`${d} 天 ${h} 小时`:h?`${h} 小时 ${m} 分钟`:`${m} 分钟`}
function num(v){return Number.isFinite(+v)?(+v).toFixed(2):'--'}
function fillClass(v){v=+v||0;return v>=85?'hot':v>=70?'warn':''}
function statusText(v){return v==='online'?'在线':v==='offline'?'离线':'等待接入'}
async function api(url,opt={}){const o={method:opt.method||'GET',headers:{...(opt.headers||{})},credentials:'same-origin'};if(opt.body!==undefined){o.headers['Content-Type']='application/json';o.body=JSON.stringify(opt.body)}if(o.method!=='GET'&&st.csrf)o.headers['X-CSRF-Token']=st.csrf;const r=await fetch(url,o);let d=null;const ct=r.headers.get('content-type')||'';if(ct.includes('json')){try{d=await r.json()}catch{}}else{d=await r.text()}if(r.status===401){if(!url.includes('/api/login')){sessionLost()}throw new Error(d?.error||'登录已失效')}if(!r.ok)throw new Error(d?.error||d?.message||`HTTP ${r.status}`);return d}
function sessionLost(){$('#app')?.classList.add('hidden');hide('settingsOverlay');hide('detailOverlay');show('loginOverlay');st.csrf=''}
async function init(){const theme=localStorage.getItem('nodelume-theme');if(theme)document.documentElement.dataset.theme=theme;$$('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));$$('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o&&!['setupOverlay','loginOverlay'].includes(o.id))hide(o.id)});wire();try{const s=await api('/api/setup/status');$('#versionTag').textContent='v'+s.server_version;$('#loginPathText').textContent=location.pathname;if(s.required){show('setupOverlay');return}try{const sess=await api('/api/session');st.csrf=sess.csrf;enterApp(sess)}catch{show('loginOverlay')}}catch(e){toast(e.message)}}
function wire(){
 $('#setupBtn').onclick=setup;$('#setupPass2').onkeydown=e=>{if(e.key==='Enter')setup()};$('#loginBtn').onclick=login;$('#loginPass').onkeydown=e=>{if(e.key==='Enter')login()};
 $('#themeBtn').onclick=toggleTheme;$('#settingsBtn').onclick=openSettings;$('#logoutBtn').onclick=logout;$('#settingsLogoutBtn').onclick=logout;$('#addBtn').onclick=openAdd;$('#mobileAddBtn').onclick=openAdd;$('#refreshBtn').onclick=refreshNodes;$('#searchInput').oninput=renderNodes;
 $('#createNodeBtn').onclick=createNode;$('#resetAddBtn').onclick=()=>{$('#addStep1').style.display='block';$('#addStep2').style.display='none';$('#nodeName').value=''};$('#copyCommand').onclick=()=>copy($('#installCommand').textContent);
 $('#tabs').onclick=tabClick;$$('.ranges').forEach(g=>g.onclick=rangeClick);$('#procSearch').oninput=()=>renderProcesses(st.processes);
 $('#confirmActionBtn').onclick=async()=>{const fn=st.confirm;st.confirm=null;hide('confirmOverlay');if(fn)await fn()};
 $('#reenrollBtn').onclick=reenroll;$('#deleteNodeBtn').onclick=deleteNode;
 $('#settingNav').onclick=e=>{const b=e.target.closest('button[data-setting]');if(!b)return;$$('#settingNav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.setting-pane').forEach(x=>x.classList.remove('active'));$('#setting-'+b.dataset.setting).classList.add('active');if(b.dataset.setting==='updates')checkUpdates();if(b.dataset.setting==='audit')loadAudit()};
 $('#saveSecurePath').onclick=saveSecurity;$('#saveProxyBtn').onclick=saveSecurity;$('#changePassBtn').onclick=changePassword;$('#domainCheckBtn').onclick=checkHTTPS;$('#domainApplyBtn').onclick=applyHTTPS;$('#certCheckBtn').onclick=checkCert;$('#certRenewBtn').onclick=checkCert;$('#httpsMode').onchange=updateHTTPSUI;$('#checkUpdatesBtn').onclick=checkUpdates;$('#serverUpdateBtn').onclick=serverUpdate;$('#allAgentUpdateBtn').onclick=allAgentUpdate;
 window.addEventListener('resize',()=>{if($('#detailOverlay').classList.contains('show'))drawCharts()});
}
async function setup(){const a=$('#setupPass').value,b=$('#setupPass2').value;if(a.length<12){toast('密码至少 12 个字符');return}if(a!==b){toast('两次密码不一致');return}try{await api('/api/setup',{method:'POST',body:{password:a}});hide('setupOverlay');const d=await api('/api/login',{method:'POST',body:{password:a}});st.csrf=d.csrf;$('#setupPass').value=$('#setupPass2').value='';enterApp(await api('/api/session'));toast('初始化完成')}catch(e){toast(e.message)}}
async function login(){const b=$('#loginBtn');b.disabled=true;$('#loginError').textContent='';try{const d=await api('/api/login',{method:'POST',body:{password:$('#loginPass').value}});st.csrf=d.csrf;$('#loginPass').value='';hide('loginOverlay');enterApp(await api('/api/session'))}catch(e){$('#loginError').textContent=e.message}finally{b.disabled=false}}
async function logout(){try{await api('/api/logout',{method:'POST',body:{}})}catch{}hide('settingsOverlay');sessionLost();toast('已退出')}
function enterApp(sess){st.csrf=sess.csrf||st.csrf;st.settings=sess.settings||{};$('#app').classList.remove('hidden');hide('loginOverlay');$('#versionTag').textContent='v'+sess.server_version;$('#settingServerVersion').textContent='v'+sess.server_version;$('#settingProtocol').textContent='v'+sess.protocol_version;refreshNodes();clearInterval(st.refreshTimer);st.refreshTimer=setInterval(refreshNodes,2000);setTimeout(checkUpdates,500)}
function toggleTheme(){const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('nodelume-theme',n);drawCharts()}
function openAdd(){$('#addStep1').style.display='block';$('#addStep2').style.display='none';$('#nodeName').value='';show('addOverlay')}
async function createNode(){const name=$('#nodeName').value.trim();if(!name){toast('请输入服务器名称');return}const b=$('#createNodeBtn');b.disabled=true;try{const d=await api('/api/nodes',{method:'POST',body:{Name:name,Group:$('#nodeGroup').value==='默认'?'':$('#nodeGroup').value}});showInstall(d.install_command,`等待「${name}」连接...`);await refreshNodes()}catch(e){toast(e.message)}finally{b.disabled=false}}
function showInstall(cmd,msg){$('#installCommand').textContent=cmd;$('#waitingText').textContent=msg;$('#addStep1').style.display='none';$('#addStep2').style.display='block';show('addOverlay')}
async function copy(t){try{await navigator.clipboard.writeText(t);toast('已复制')}catch{toast('复制失败，请手动复制')}}
async function refreshNodes(){if(document.hidden)return;try{st.nodes=await api('/api/nodes');renderNodes();if(st.current){const n=st.nodes.find(x=>x.ID===st.current.ID||x.id===st.current.id);if(n){st.current=n;renderDetail(n)}}}catch(e){if(!String(e.message).includes('登录'))console.warn(e)}}
function normNode(n){return {id:n.ID||n.id,name:n.Name||n.name,group:n.Group||n.group,status:n.Status||n.status,created_at:n.CreatedAt||n.created_at,last_seen:n.LastSeen||n.last_seen,latest:n.Latest||n.latest||{},system:n.System||n.system||{}}}
function renderNodes(){const q=$('#searchInput').value.trim().toLowerCase();const ns=st.nodes.map(normNode);const online=ns.filter(n=>n.status==='online').length,offline=ns.filter(n=>n.status==='offline').length;$('#totalServers').textContent=ns.length;$('#onlineServers').textContent=online;$('#offlineServers').textContent=offline;const g=$('#serverGrid');const list=ns.filter(n=>(n.name+' '+n.group+' '+(n.system.os||'')).toLowerCase().includes(q));if(!list.length){g.innerHTML='<div class="empty">暂无服务器</div>';return}g.innerHTML=list.map(n=>{const l=n.latest||{},on=n.status==='online';return `<article class="server ${on?'':'offline'}" data-node="${esc(n.id)}"><div class="server-head"><div class="server-title"><div class="flag">◈</div><div><div class="name">${esc(n.name)}</div><div class="meta">${esc(n.system.os||'尚未接入')} · ${esc(n.system.arch||'--')} ${n.group?'· '+esc(n.group):''}</div></div></div><div class="status"><span class="sdot"></span><span>${statusText(n.status)}</span></div></div><div class="metrics">${metric('CPU',l.cpu,on)}${metric('内存',l.memory,on)}${metric('磁盘',l.disk,on||n.status==='offline')}</div><div class="server-foot"><div><div class="footval">↑ ${on?fmtRate(l.net_out):'--'}</div><div class="footlbl">上传</div></div><div><div class="footval">↓ ${on?fmtRate(l.net_in):'--'}</div><div class="footlbl">下载</div></div><div><div class="footval">${n.system.agent?'v'+esc(n.system.agent):'--'}</div><div class="footlbl">Agent</div></div></div></article>`}).join('');g.querySelectorAll('[data-node]').forEach(x=>x.onclick=()=>openDetail(x.dataset.node))}
function metric(n,v,ok){v=+v||0;return `<div class="metric"><div class="row"><span>${n}</span><b>${ok?fmtPct(v):'--'}</b></div><div class="bar"><div class="fill ${fillClass(v)}" style="width:${ok?Math.max(0,Math.min(100,v)):0}%"></div></div></div>`}
function openDetail(id){const n=st.nodes.map(normNode).find(x=>x.id===id);if(!n)return;st.current=n;st.range=1;$$('.range').forEach(b=>b.classList.toggle('active',+b.dataset.range===1));$$('#tabs .tab').forEach((b,i)=>b.classList.toggle('active',i===0));$$('.tabpane').forEach((p,i)=>p.classList.toggle('active',i===0));renderDetail(n);show('detailOverlay');if(n.status==='online')loadHistory();else{st.history=[];drawCharts()}}
function renderDetail(n){const l=n.latest||{},s=n.system||{},on=n.status==='online';$('#dName').textContent=n.name;$('#dMeta').textContent=`${s.os||'尚未接入'} · ${s.arch||'--'} · Agent ${s.agent?'v'+s.agent:'--'}`;$('#detailStatusText').textContent=statusText(n.status);$('#detailStatusDot').style.background=on?'var(--green)':'var(--red)';$('#offlineBanner').style.display=on?'none':'block';$$('#tabs .tab').forEach(b=>{if(['cpu','memory','disk','process','stopped'].includes(b.dataset.tab))b.disabled=!on});setBox('dcpu','dcpuBar',l.cpu,on||n.status==='offline');setBox('dram','dramBar',l.memory,on||n.status==='offline');setBox('ddisk','ddiskBar',l.disk,on||n.status==='offline');$('#dtemp').textContent=l.temperature!=null?Math.round(l.temperature)+'℃':'--';$('#dnet').textContent=on?`↑ ${fmtRate(l.net_out)}　↓ ${fmtRate(l.net_in)}`:'--';$('#dload').textContent=l.load1!=null?`${num(l.load1)} / ${num(l.load5)} / ${num(l.load15)}`:'--';$('#duptime').textContent=l.uptime!=null?fmtUptime(l.uptime):'--';$('#procCount').textContent=l.processes??'--';$('#cpuModel').textContent=s.cpu_model||'--';$('#cpuCores').textContent=s.cpu_cores?`${s.cpu_cores} 核`:'--';$('#cpuNow').textContent=on?fmtPct(l.cpu):'--';$('#cpuLoad').textContent=on?`${num(l.load1)} / ${num(l.load5)} / ${num(l.load15)}`:'--';$('#memTotal').textContent=s.memory_total?fmtBytes(s.memory_total):'--';$('#memUsed').textContent=on?fmtBytes(l.memory_used):'--';$('#memAvail').textContent=on?fmtBytes(l.memory_available):'--';$('#memNow').textContent=on?fmtPct(l.memory):'--';renderProcTable($('#cpuProcTable'),l.top_cpu||[]);renderProcTable($('#memProcTable'),l.top_memory||[]);$('#sysHostname').textContent=s.hostname||'--';$('#sysOS').textContent=s.os||'--';$('#sysKernel').textContent=s.kernel||'--';$('#sysArch').textContent=s.arch||'--';$('#sysAgent').textContent=s.agent?'NodeLume Agent v'+s.agent:'--';$('#sysProtocol').textContent=s.protocol?'Protocol v'+s.protocol:'--';$('#sysHeartbeat').textContent=n.last_seen?new Date(n.last_seen*1000).toLocaleString():'--'}
function setBox(v,b,n,ok){$('#'+v).textContent=ok?fmtPct(n):'--';const el=$('#'+b);if(el){el.style.width=ok?Math.max(0,Math.min(100,+n||0))+'%':'0';el.className='fill '+fillClass(n)}}
async function loadHistory(){if(!st.current||st.current.status!=='online'){st.history=[];drawCharts();return}try{st.history=await api(`/api/nodes/${encodeURIComponent(st.current.id)}/history?minutes=${st.range}`);drawCharts()}catch(e){toast(e.message)}}
function rangeClick(e){const b=e.target.closest('.range');if(!b)return;const g=b.closest('.ranges');g.querySelectorAll('.range').forEach(x=>x.classList.remove('active'));b.classList.add('active');st.range=+b.dataset.range;$$('.ranges').forEach(other=>{if(other!==g)other.querySelectorAll('.range').forEach(x=>x.classList.toggle('active',+x.dataset.range===st.range))});loadHistory()}
function drawCharts(){drawChart('overviewChart','cpu','CPU');drawChart('cpuChart','cpu','CPU');drawChart('memChart','memory','内存')}
function drawChart(id,key,label){const c=$('#'+id);if(!c)return;const rect=c.getBoundingClientRect();if(rect.width<30)return;const dpr=devicePixelRatio||1,w=rect.width,h=190;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);const css=getComputedStyle(document.documentElement),grid=css.getPropertyValue('--line').trim(),muted=css.getPropertyValue('--muted').trim(),green=css.getPropertyValue('--green').trim();const m={l:45,r:10,t:12,b:30},pw=w-m.l-m.r,ph=h-m.t-m.b;x.clearRect(0,0,w,h);x.font='10px system-ui';x.fillStyle=muted;x.strokeStyle=grid;x.lineWidth=1;[0,25,50,75,100].forEach(v=>{const y=m.t+ph-v/100*ph;x.beginPath();x.moveTo(m.l,y);x.lineTo(w-m.r,y);x.stroke();x.textAlign='right';x.fillText(v+'%',m.l-6,y+3)});for(let i=0;i<=4;i++){const px=m.l+i/4*pw;x.beginPath();x.moveTo(px,m.t);x.lineTo(px,m.t+ph);x.stroke();const ago=st.range*(1-i/4);let t=ago===0?'现在':st.range===1?Math.round(ago*60)+'秒前':Math.round(ago)+'分钟前';if(st.range===60&&ago===60)t='1小时前';x.textAlign=i===0?'left':i===4?'right':'center';x.fillText(t,px,h-8)}const pts=st.history||[];if(!pts.length){x.textAlign='center';x.fillText('暂无历史数据',m.l+pw/2,m.t+ph/2);return}const start=Date.now()/1000-st.range*60,now=Date.now()/1000;x.strokeStyle=green;x.lineWidth=2;x.beginPath();let begun=false;pts.forEach(p=>{const px=m.l+Math.max(0,Math.min(1,(p.t-start)/(now-start)))*pw,py=m.t+ph-Math.max(0,Math.min(100,+p[key]||0))/100*ph;if(!begun){x.moveTo(px,py);begun=true}else x.lineTo(px,py)});x.stroke()}
async function tabClick(e){const b=e.target.closest('.tab');if(!b||b.disabled)return;$$('#tabs .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tabpane').forEach(x=>x.classList.remove('active'));$('#pane-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='process')await loadProcesses();if(b.dataset.tab==='stopped')await loadStopped();if(b.dataset.tab==='disk')await loadDisks();if(['overview','cpu','memory'].includes(b.dataset.tab))drawCharts()}
function processTable(list){return `<div class="tablewrap process-table"><table><thead><tr><th>PID</th><th>进程</th><th>CPU</th><th>内存</th><th>用户</th><th>状态</th></tr></thead><tbody>${list.map(p=>`<tr class="clickable" data-pid="${+p.pid}"><td>${+p.pid}</td><td class="procname">${esc(p.name)}</td><td>${num(p.cpu)}%</td><td>${fmtBytes((+p.memory_mb||0)*1048576)}</td><td>${esc(p.user||'--')}</td><td><span class="badge">${esc(p.state||'--')}</span></td></tr>`).join('')}</tbody></table></div>`}
function renderProcTable(root,list){root.innerHTML=list.length?processTable(list):'<div class="empty">暂无数据</div>';root.querySelectorAll('[data-pid]').forEach(r=>r.onclick=()=>openProcess(+r.dataset.pid))}
async function loadProcesses(){if(!st.current||st.current.status!=='online')return;$('#allProcTable').innerHTML='<div class="empty">正在读取进程...</div>';try{st.processes=await api(`/api/nodes/${encodeURIComponent(st.current.id)}/processes`);renderProcesses(st.processes)}catch(e){$('#allProcTable').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderProcesses(list){const q=$('#procSearch').value.trim().toLowerCase(),f=list.filter(p=>!q||(p.name||'').toLowerCase().includes(q)||String(p.pid).includes(q)||(p.user||'').toLowerCase().includes(q));renderProcTable($('#allProcTable'),f)}
async function openProcess(pid){try{const p=await api(`/api/nodes/${encodeURIComponent(st.current.id)}/process/${pid}`);st.currentProc=p;$('#pName').textContent=p.name||'进程';$('#pPid').textContent=p.pid;$('#pState').innerHTML=`<span class="badge">${esc(p.state||'--')}</span>`;$('#pCpu').textContent=num(p.cpu)+'%';$('#pMem').textContent=fmtBytes((+p.memory_mb||0)*1048576);$('#pUser').textContent=p.user||'--';$('#pLaunch').textContent=p.launch||'--';$('#pService').textContent=p.service||'--';$('#pParent').textContent=p.parent||'--';$('#pExe').textContent=p.exe||'--';$('#pCwd').textContent=p.cwd||'--';$('#pCmd').textContent=p.command||'--';$('#pTree').textContent=p.tree||'--';$('#pNote').textContent=p.note||'';$('#pNote').style.display=p.note?'block':'none';renderProcActions(p);show('procOverlay')}catch(e){toast(e.message)}}
function renderProcActions(p){const a=$('#procActions');a.innerHTML='<button class="btn" id="closeProc">关闭</button>';$('#closeProc').onclick=()=>hide('procOverlay');if(p.protected){a.insertAdjacentHTML('beforeend','<button class="btn" disabled>受保护，不允许控制</button>');return}if(p.restart_mode==='systemd'&&p.launch==='systemd 服务'){a.insertAdjacentHTML('beforeend','<button class="btn" id="stopSvc">停止服务</button><button class="btn primary" id="restartProc">重启服务</button>');$('#stopSvc').onclick=()=>confirmProcess('service_stop');$('#restartProc').onclick=()=>confirmProcess('service_restart');return}if(p.can_terminate){a.insertAdjacentHTML('beforeend','<button class="btn danger" id="termProc">终止进程</button>');$('#termProc').onclick=()=>confirmProcess('terminate')}if(p.can_restart){a.insertAdjacentHTML('beforeend',`<button class="btn primary" id="restartProc">${p.restart_mode==='systemd'?'重启所属服务':'重启进程'}</button>`);$('#restartProc').onclick=()=>confirmProcess(p.restart_mode==='systemd'?'service_restart':'restart')}}
function confirmProcess(action){const p=st.currentProc;const names={terminate:'终止进程',restart:'重启进程',service_restart:'重启服务',service_stop:'停止服务',kill:'强制终止'};let note=action==='kill'?'将发送 SIGKILL。该动作不可撤销。':'Agent 只执行固定白名单协议，不会调用 Shell。';if(action==='terminate'&&!p.can_restart)note+=(p.note?' '+p.note:' 此进程终止后 NodeLume 不保证能够重新启动。');confirmBox(names[action],`确定对 <b>${esc(p.name)}</b> (PID ${p.pid}) 执行「${names[action]}」吗？`,note,()=>doProcessAction(action))}
async function doProcessAction(action){try{await api(`/api/nodes/${encodeURIComponent(st.current.id)}/process/${st.currentProc.pid}/action`,{method:'POST',body:{action}});hide('procOverlay');toast(action==='kill'?'进程已强制终止':'操作成功');await loadProcesses();if(action==='terminate'||action==='kill')await loadStopped()}catch(e){if(action==='terminate'&&st.currentProc&&st.currentProc.can_kill&&String(e.message).includes('SIGTERM')){confirmBox('进程仍在运行',`<b>${esc(st.currentProc.name)}</b> 未响应 SIGTERM。是否强制终止？`,'将发送 SIGKILL。该动作不可撤销，仅在正常终止失败后使用。',()=>doProcessAction('kill'));return}toast(e.message)}}
async function loadStopped(){if(!st.current||st.current.status!=='online')return;try{const rows=await api(`/api/nodes/${encodeURIComponent(st.current.id)}/stopped`);const root=$('#stoppedProcTable');if(!rows.length){root.innerHTML='<div class="empty">暂无可安全恢复的已停止项目</div>';return}root.innerHTML=`<div class="tablewrap"><table><thead><tr><th>名称</th><th>启动方式</th><th>服务</th><th>停止时间</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="procname">${esc(r.name)}</td><td>${esc(r.launch)}</td><td>${esc(r.service||'--')}</td><td>${new Date(r.stopped_at*1000).toLocaleString()}</td><td>${r.can_start?`<button class="btn small start-saved" data-rid="${esc(r.id)}">启动</button>`:'--'}</td></tr>`).join('')}</tbody></table></div>`;root.querySelectorAll('.start-saved').forEach(b=>b.onclick=()=>confirmBox('启动已停止项目','确定按 Agent 本机保存的安全启动快照重新启动吗？','不会读取环境变量，也不会通过 Shell 执行。',()=>startSaved(b.dataset.rid)))}catch(e){$('#stoppedProcTable').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function startSaved(rid){try{await api(`/api/nodes/${encodeURIComponent(st.current.id)}/stopped/${encodeURIComponent(rid)}/start`,{method:'POST',body:{}});toast('启动成功');loadStopped()}catch(e){toast(e.message)}}
async function loadDisks(){try{const d=await api(`/api/nodes/${encodeURIComponent(st.current.id)}/disks`);$('#diskTable').innerHTML=d.length?`<div class="tablewrap"><table><thead><tr><th>设备</th><th>挂载点</th><th>文件系统</th><th>已用</th><th>总量</th><th>使用率</th></tr></thead><tbody>${d.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.mount)}</td><td>${esc(x.fs_type)}</td><td>${fmtBytes(x.used)}</td><td>${fmtBytes(x.total)}</td><td>${fmtPct(x.percent)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">未发现文件系统</div>'}catch(e){$('#diskTable').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function confirmBox(title,text,note,fn){$('#confirmTitle').textContent=title;$('#confirmText').innerHTML=text;$('#confirmNote').textContent=note;st.confirm=fn;show('confirmOverlay')}
async function reenroll(){if(!st.current)return;confirmBox('重新接入节点',`为「${esc(st.current.name)}」生成新的接入命令吗？`,'当前 Agent 在新的 Agent 成功注册前继续保持有效。',async()=>{try{const d=await api(`/api/nodes/${encodeURIComponent(st.current.id)}/reenroll`,{method:'POST',body:{}});hide('detailOverlay');showInstall(d.install_command,'等待新的 Agent 注册；旧 Agent 当前仍有效');toast('新的接入命令已生成')}catch(e){toast(e.message)}})}
async function deleteNode(){if(!st.current)return;confirmBox('删除节点',`确定删除「${esc(st.current.name)}」吗？`,'删除后当前 Agent 凭据立即失效，此操作不可撤销。',async()=>{try{await api(`/api/nodes/${encodeURIComponent(st.current.id)}`,{method:'DELETE',body:{}});hide('detailOverlay');st.current=null;toast('节点已删除');refreshNodes()}catch(e){toast(e.message)}})}
async function openSettings(){show('settingsOverlay');try{const d=await api('/api/settings');st.settings=d.settings;$('#settingServerVersion').textContent='v'+d.server_version;$('#settingProtocol').textContent='v'+d.protocol_version;$('#securePath').value=d.settings.admin_path||'/';$('#trustedProxy').value=(d.settings.trusted_proxies||[]).join(', ');$('#domainInput').value=d.settings.domain||'';$('#httpsMode').value=d.settings.https_mode||'off';renderCert(d.certificate);updateHTTPSUI()}catch(e){toast(e.message)}loadAudit()}
async function saveSecurity(){const p=$('#securePath').value.trim()||'/',proxies=$('#trustedProxy').value.split(',').map(x=>x.trim()).filter(Boolean);try{const d=await api('/api/settings/security',{method:'POST',body:{admin_path:p,trusted_proxies:proxies}});st.settings={...(st.settings||{}),admin_path:d.admin_path,trusted_proxies:proxies};toast('安全设置已保存');if(location.pathname!==d.admin_path){toast('管理入口已修改，下次请使用新入口')}}catch(e){toast(e.message)}}
async function changePassword(){const old=$('#oldPass').value,n=$('#newPass').value,n2=$('#newPass2').value;if(n.length<12)return toast('新密码至少 12 个字符');if(n!==n2)return toast('两次新密码不一致');confirmBox('修改管理员密码','修改后会撤销所有已登录会话。','你需要使用新密码重新登录。',async()=>{try{await api('/api/settings/password',{method:'POST',body:{current:old,new:n}});$('#oldPass').value=$('#newPass').value=$('#newPass2').value='';hide('settingsOverlay');sessionLost();toast('密码已修改，请重新登录')}catch(e){toast(e.message)}})}
function updateHTTPSUI(){$('#acmeSection').style.display=$('#httpsMode').value==='builtin'?'block':'none'}
async function checkHTTPS(){try{const d=await api('/api/settings/https/check',{method:'POST',body:{domain:$('#domainInput').value.trim(),mode:$('#httpsMode').value}});toast(d.dns_warning?'配置可用，但 DNS 尚未解析':'配置检查通过')}catch(e){toast(e.message)}}
async function applyHTTPS(){const domain=$('#domainInput').value.trim(),mode=$('#httpsMode').value;confirmBox('应用域名与 HTTPS',mode==='off'?'确定关闭 NodeLume 内置/声明的 HTTPS 模式吗？':`确定应用 <b>${esc(domain)}</b>（${esc(mode)}）吗？`,'已有 Agent 时，请确保旧地址继续可用，Agent 只会在验证新 HTTPS 端点成功后迁移。',async()=>{try{const d=await api('/api/settings/https/apply',{method:'POST',body:{domain,mode}});st.settings=d.settings;renderCert(d.certificate);updateHTTPSUI();toast('HTTPS 设置已应用')}catch(e){toast(e.message)}})}
async function checkCert(){try{const d=await api('/api/settings/certificate/check',{method:'POST',body:{}});renderCert(d);toast('证书检查完成')}catch(e){toast(e.message)}}
function renderCert(c){c=c||{};$('#certStatus').innerHTML=c.status==='valid'?'<span class="badge">有效</span>':c.status==='renewal_due'?'<span class="badge warn">即将续期</span>':`<span class="badge off">${esc(c.status||'未管理')}</span>`;$('#certExpiry').textContent=c.not_after?new Date(c.not_after*1000).toLocaleDateString():'--';$('#certAuto').textContent=c.auto_renew?'开启':'关闭'}
async function loadAudit(){try{const d=await api('/api/audit');$('#auditList').innerHTML=d.length?d.map(a=>`<div class="audit-item"><div class="time">${new Date(a.time*1000).toLocaleString()} · ${esc(a.ip||'')}</div><b>${esc(a.action)}</b>${a.node?' · '+esc(a.node):''}<div class="hint">${esc(a.detail||'')} · ${esc(a.result)}</div></div>`).join(''):'<div class="empty">暂无审计记录</div>'}catch(e){$('#auditList').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function checkUpdates(){try{const d=await api('/api/update/status');st.update=d;const latest=d.latest_version||'--';$('#serverVersionMeta').textContent=`当前 v${d.server_version} · 最新 ${latest==='--'?'--':'v'+latest} · Protocol v${d.protocol_version}`;const agents=d.agents||[],online=agents.filter(a=>a.status==='online').length,avail=latest==='--'?0:agents.filter(a=>a.status==='online'&&cmp(a.version,latest)<0).length;$('#agentUpdateMeta').textContent=`${online} 在线 · ${avail} 台可更新`;renderAgentUpdates(agents,latest);if(d.error){$('#serverUpdateText').textContent='检查更新失败：'+d.error;$('#serverUpdateBtn').disabled=true;$('#updateSummary').textContent='检查失败';$('#updateSummarySub').textContent='无法连接 Release 源';return}const total=(d.server_update_available?1:0)+avail;$('#updateSummary').textContent=total?`${total} 项可更新`:'已是最新';$('#updateSummarySub').textContent=`Server ${d.server_update_available?'可更新':'最新'} · ${avail} 个 Agent 可更新`;$('#serverUpdateBtn').disabled=!d.server_update_available||d.incompatible_agents>0;$('#serverUpdateText').textContent=d.incompatible_agents?`⚠ ${d.incompatible_agents} 个 Agent 不兼容，请先更新 Agent`:d.server_update_available?'✓ 协议兼容，可安全更新':'✓ Server 已是最新';if(d.server_update_status){const u=d.server_update_status;$('#serverUpdateText').textContent=`${u.state}: ${u.message}`}}catch(e){$('#serverUpdateText').textContent='检查更新失败：'+e.message}}
function cmp(a,b){const x=String(a||'0.0.0').replace(/^v/,'').split('.').map(Number),y=String(b||'0.0.0').replace(/^v/,'').split('.').map(Number);for(let i=0;i<3;i++){if((x[i]||0)<(y[i]||0))return-1;if((x[i]||0)>(y[i]||0))return 1}return 0}
function renderAgentUpdates(agents,latest){const root=$('#agentUpdateRows');root.innerHTML=agents.map(a=>{const can=a.status==='online'&&latest!=='--'&&cmp(a.version,latest)<0;return `<tr><td>${esc(a.name)}</td><td>${a.version?'v'+esc(a.version):'--'}</td><td>${latest==='--'?'--':'v'+esc(latest)}</td><td><span class="badge ${a.status==='online'?'':'off'}">${esc(statusText(a.status))}</span></td><td>${can?`<button class="btn small agent-update" data-id="${esc(a.id)}">更新</button>`:'--'}</td></tr>`}).join('');root.querySelectorAll('.agent-update').forEach(b=>b.onclick=()=>agentUpdate(b.dataset.id,latest))}
async function agentUpdate(id,version){const a=st.update?.agents?.find(x=>x.id===id);confirmBox('更新 Agent',`确定将「${esc(a?.name||id)}」更新到 v${esc(version)} 吗？`,'更新采用签名校验、备份、重启健康检查；失败会自动恢复上一版本。',async()=>{try{await api(`/api/nodes/${encodeURIComponent(id)}/update`,{method:'POST',body:{version}});toast('Agent 更新已开始');setTimeout(checkUpdates,5000)}catch(e){toast(e.message)}})}
async function allAgentUpdate(){const d=st.update;if(!d?.latest_version)return;const list=(d.agents||[]).filter(a=>a.status==='online'&&cmp(a.version,d.latest_version)<0);if(!list.length)return toast('没有可更新的在线 Agent');confirmBox('批量更新 Agent',`将按顺序更新 ${list.length} 台在线 Agent。`,'为了降低风险，Web 会逐台执行；单台失败不会继续假装成功。',async()=>{for(const a of list){try{toast(`正在更新 ${a.name}`);await api(`/api/nodes/${encodeURIComponent(a.id)}/update`,{method:'POST',body:{version:d.latest_version}});await new Promise(r=>setTimeout(r,1800))}catch(e){toast(`${a.name} 更新失败：${e.message}`);break}}setTimeout(checkUpdates,3000)})}
async function serverUpdate(){const d=st.update;if(!d?.latest_version)return;confirmBox('更新 NodeLume Server',`确定将 Server 从 v${esc(d.server_version)} 更新到 v${esc(d.latest_version)} 吗？`,'更新器会验证 Ed25519 + SHA256、self-check、备份和健康检查；失败自动回滚。Agent 会在 Server 短暂重启后自动重连。',async()=>{try{await api('/api/update/server',{method:'POST',body:{version:d.latest_version}});$('#serverUpdateText').textContent='更新已排队，等待 systemd 更新器执行...';toast('Server 更新已排队');pollAfterServerUpdate()}catch(e){toast(e.message)}})}
async function pollAfterServerUpdate(){let i=0;const timer=setInterval(async()=>{i++;try{const r=await fetch('/healthz',{cache:'no-store'});if(r.ok){clearInterval(timer);setTimeout(checkUpdates,1000)}}catch{}if(i>45)clearInterval(timer)},1000)}
init();
